#pragma once

#include <iostream>
#include <vector>
#include <string>
#include "discord.h"
#include "log.h"


inline std::vector<FString> PlayerBotNames;

static inline void InitBotNames()
{
    PlayerBotNames.clear();

    PlayerBotNames =
    {
        L"[EPIC] Tim Sweeney",
        L"[EPIC] MagmaReef",
        L"[Rift] Makks",
        L"[Era] SizzyFNBRLeaks",
        L"[EOR] Nyaai",
        L"[Chronos] parkie",
        L"[1crAp] IdystFatass",
        L"Samicc/FortniteBuilds",
        L"KyiroEasyInstaller",
        L"[Nova] Ender0001",
        L"[OnyxFN] Jacobb626YT",
        L"SLL Bypass Patched",
        L"[Nova] Sammy",
        L"[Beyond] Twin2",
        L"[Trannies] Ploosh",
        L"[Trannies] Skies",
        L"[Trannies] Jagger",
        L"[Femboys] Forty",
        L"[Sonic Game] array0x",
        L"[FMod Linora] Android1337",
        L"[Greek] Skidaim",
        L"[EZFN] Lupus joel",
        L"[LawinServer] Lawin",
        L"TeamKillerOzne",
        L"[Fatasses] Soggs",
        L"[Polaris V2] Cyuubi",
        L"[Dumper-7] Fischsalat",
        L"[Retrac] Zombie Man 16k Tokens",
        L"[Retrac] 0xKAEDE KSKID",
        L"[Retrac] Blur",
        L"GDBOI101",
        L"FortPickle",
        L"FortMP is era not twin1",
        L"[Nova] Kyiro sakcnana",
        L"Fmod wasnt tokenlogger",
        L"Googlecheats karma",
        L"[REtard] 1shotfishy",
        L"[REtard] Marvelco",
        L"[Twin1] Twin towers",
        L"Dyno [ BOT \u2705 ]",
        L"[JEWS] Riko",
        L"[REtard PEDO] spooky",
        L"[REtard ezfn] anto",
        L"[REtard ezfn] represoh",
        L"[REtard] Timmie Doesnt develop",
        L"[Project Reboot] Milf nor",
        L"[Cheater] Custox",
        L"[greeKS] Wiks wiks",
        L"ShieldMP",
        L"[Fat] Biggins",
        L"[Aurora V2] Brianna",
        L"PeQuFNBRLeaks",
        L"[ChannelMP] ZETAX",
        L"Huggo",
        L"[SizzyFNBRLeaks] Era",
        L"Text channel #general",
        L"Radmin vpn",
        L"Logmein hamachi riftmp",
        L"Zerotier I FUCKING HATE YOU",
        L"[Fat] Threxo",
        L"[WGS] WiktorWiktor12 Bri ish",
        L"[Reboot UltimateSkid] Max",
        L"[Skidduh] Magmadev",
        L"[Makks] RiftMp",
        L"[Beat] Aurora.Runtime",
        L"[Cheatuhhhh] Random",
        L"[UePak] Zylox",
        L"[RetARD] Sali",
        L"[RetARD] Grapz",
        L"Fortnite.Tools 13.40 StormFn S13 full games",
        L"5 Minute no kick",
        L"[Hosting] Epic",
        L"[Sulfur top 1 skid] Jaysen",
        L"[FAREX] Fmof",
        L"[Idfk] Noggo",
        L"McMistrzYt",
        L"[StormFN S13] Stormzy",
        L"FaZe Cinardere",
        L"[Eon] Charles",
        L"[Turkey] Hxnted",
        L"[Yt view farmer] Mineluke",
        L"[Rythm] Ryhtm",
        L"SwAyZz",
        L"Eon owner rio tokenlog",
        L"[FLIPPED] Not tacs",
        L"Flipped minus 2k members epic nuke by parkie",
        L"ElixirFN",
        L"BetterFN",
        L"[Flopper] Mstreem",
        L"[Trannies] Zinx",
        L"Default idk what he did no name",
        L"[Trannies] Neva",
        L"[SKIDZ] burlone SKId",
        L"[LowTaperFade] Ninja",
        L"[4.5] Crash log",
        L"EOR.dll",
        L"[Manora] MaTiD",
        L"[harmony]JYZO",
        L"[Chikcen] Miles"
    };
}
